from ml.benchmark_compare import compare_policies
for seed in [42, 100, 777, 999, 2024]:
    res = compare_policies(seed)
    print(f'=== Seed {seed} ===')
    print(f'  Baseline Interventions: {res["baseline"]["recovery_attempts"]}')
    print(f'  AI       Interventions: {res["ai"]["recovery_attempts"]}')
    print(f'  Baseline Recovered Orders: {res["baseline"]["recovered_orders"]}')
    print(f'  AI       Recovered Orders: {res["ai"]["recovered_orders"]}')
    print(f'  Baseline Recovered Revenue: {res["baseline"]["recovered_revenue"]}')
    print(f'  AI       Recovered Revenue: {res["ai"]["recovered_revenue"]}')
    print(f'  Baseline Recovery Rate: {res["baseline"]["recovery_rate"]:.4f}')
    print(f'  AI       Recovery Rate: {res["ai"]["recovery_rate"]:.4f}')
    print(f'  Baseline RR Rate: {res["baseline"]["revenue_recovery_rate"]:.4f}')
    print(f'  AI       RR Rate: {res["ai"]["revenue_recovery_rate"]:.4f}')
    b_per_int = res["baseline"]["recovered_revenue"] / max(1, res["baseline"]["recovery_attempts"])
    a_per_int = res["ai"]["recovered_revenue"] / max(1, res["ai"]["recovery_attempts"])
    print(f'  Baseline Revenue/Intervention: {b_per_int:.2f}')
    print(f'  AI       Revenue/Intervention: {a_per_int:.2f}')
    print(f'  Baseline Unnecessary: {res["baseline"]["unnecessary_interventions"]}')
    print(f'  AI       Unnecessary: {res["ai"]["unnecessary_interventions"]}')
    print(f'  Baseline Exhausted: {res["baseline"]["exhausted_cases"]}')
    print(f'  AI       Exhausted: {res["ai"]["exhausted_cases"]}')
